//*******************************************************************
//    pdrdata.h
//
//    This is an example header file that can be used with code emitted
//    from pdrmaker. 
//    
//    Portions of this code are based on the Platform Level Data Model
//    (PLDM) specifications from the Distributed Management Task Force 
//    (DMTF).  More information about PLDM can be found on the DMTF
//    web site (www.dmtf.org).
//
//    More information on the PICMG IoT data model can be found within
//    the PICMG family of IoT specifications.  For more information,
//    please visit the PICMG web site (www.picmg.org)
//
//    Copyright (C) 2020,  PICMG
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
#pragma once
#include <avr/pgmspace.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SAMPLE_RATE 4000
typedef signed long FIXEDPOINT_24_8;

#define PDR_BYTE_TYPE const unsigned char
#define PDR_DATA_ATTRIBUTES PROGMEM

extern PDR_BYTE_TYPE __pdr_data[] PDR_DATA_ATTRIBUTES;
extern unsigned int __pdr_total_size;
extern unsigned int __pdr_number_of_records;
extern unsigned int __pdr_max_record_size;

#ifdef __cplusplus
}
#endif

//============================================================================
//====================
// Module-Related Macros
#define ATMEGA328PB

//====================
// PDR-Related Macros
extern PDR_BYTE_TYPE __pdr_data[] PDR_DATA_ATTRIBUTES;
#define PDR_TOTAL_SIZE 881
#define PDR_NUMBER_OF_RECORDS 19
#define PDR_MAX_RECORD_SIZE 174

//====================
// FRU-Related Macros
#define FRU_TABLE_MAXIMUM_SIZE 0
#define FRU_TOTAL_SIZE 43
#define FRU_TOTAL_RECORD_SETS 1
#define FRU_NUMBER_OF_RECORDS 2
#define FRU_MAX_RECORD_SIZE 29

//====================
// Channel-Related Macros
#define CHANNEL_INTERLOCK_OUT
#define CHANNEL_INTERLOCK_IN
#define CHANNEL_TRIGGER_OUT
#define CHANNEL_TRIGGER_IN
#define CHANNEL_DIGITAL_IN1
#define CHANNEL_DIGITAL_IN2
#define CHANNEL_STEP_DIR_OUT1

//====================
// Logical Entity-Related Macros
#define ENTITY_STEPPER1
#define ENTITY_STEPPER1_GLOBALINTERLOCKEFFECTER
#define ENTITY_STEPPER1_GLOBALINTERLOCKEFFECTER_BINDINGTYPE_STATEEFFECTER
#define ENTITY_STEPPER1_GLOBALINTERLOCKEFFECTER_EFFECTERID 1
#define ENTITY_STEPPER1_GLOBALINTERLOCKEFFECTER_BOUNDCHANNEL_INTERLOCK_OUT
#define ENTITY_STEPPER1_GLOBALINTERLOCKEFFECTER_STATEWHENHIGH 2
#define ENTITY_STEPPER1_GLOBALINTERLOCKEFFECTER_STATEWHENLOW 1
#define ENTITY_STEPPER1_GLOBALINTERLOCKSENSOR
#define ENTITY_STEPPER1_GLOBALINTERLOCKSENSOR_BINDINGTYPE_STATESENSOR
#define ENTITY_STEPPER1_GLOBALINTERLOCKSENSOR_SENSORID 1
#define ENTITY_STEPPER1_GLOBALINTERLOCKSENSOR_BOUNDCHANNEL_INTERLOCK_IN
#define ENTITY_STEPPER1_GLOBALINTERLOCKSENSOR_STATEWHENHIGH 2
#define ENTITY_STEPPER1_GLOBALINTERLOCKSENSOR_STATEWHENLOW 1
#define ENTITY_STEPPER1_TRIGGEREFFECTER
#define ENTITY_STEPPER1_TRIGGEREFFECTER_BINDINGTYPE_STATEEFFECTER
#define ENTITY_STEPPER1_TRIGGEREFFECTER_EFFECTERID 2
#define ENTITY_STEPPER1_TRIGGEREFFECTER_BOUNDCHANNEL_TRIGGER_OUT
#define ENTITY_STEPPER1_TRIGGEREFFECTER_STATEWHENHIGH 2
#define ENTITY_STEPPER1_TRIGGEREFFECTER_STATEWHENLOW 1
#define ENTITY_STEPPER1_TRIGGERSENSOR
#define ENTITY_STEPPER1_TRIGGERSENSOR_BINDINGTYPE_STATESENSOR
#define ENTITY_STEPPER1_TRIGGERSENSOR_SENSORID 2
#define ENTITY_STEPPER1_TRIGGERSENSOR_BOUNDCHANNEL_TRIGGER_IN
#define ENTITY_STEPPER1_TRIGGERSENSOR_STATEWHENHIGH 2
#define ENTITY_STEPPER1_TRIGGERSENSOR_STATEWHENLOW 1
#define ENTITY_STEPPER1_POSITION
#define ENTITY_STEPPER1_POSITION_BINDINGTYPE_NUMERICSENSOR
#define ENTITY_STEPPER1_POSITION_SENSORID 7
#define ENTITY_STEPPER1_POSITION_DEFAULT_THRESHOLDUPPERFATAL 2147483647
#define ENTITY_STEPPER1_POSITION_DEFAULT_THRESHOLDUPPERCRITICAL 2147483646
#define ENTITY_STEPPER1_POSITION_DEFAULT_THRESHOLDUPPERWARNING 2147483645
#define ENTITY_STEPPER1_POSITION_DEFAULT_THRESHOLDLOWERWARNING -2147483645
#define ENTITY_STEPPER1_POSITION_DEFAULT_THRESHOLDLOWERCRITICAL -2147483646
#define ENTITY_STEPPER1_POSITION_DEFAULT_THRESHOLDLOWERFATAL -2147483647
#define ENTITY_STEPPER1_POSITION_THRESHOLDENABLES 63
#define ENTITY_STEPPER1_POSITIVELIMIT
#define ENTITY_STEPPER1_POSITIVELIMIT_BINDINGTYPE_STATESENSOR
#define ENTITY_STEPPER1_POSITIVELIMIT_SENSORID 8
#define ENTITY_STEPPER1_POSITIVELIMIT_BOUNDCHANNEL_DIGITAL_IN1
#define ENTITY_STEPPER1_POSITIVELIMIT_STATEWHENHIGH 2
#define ENTITY_STEPPER1_POSITIVELIMIT_STATEWHENLOW 1
#define ENTITY_STEPPER1_NEGATIVELIMIT
#define ENTITY_STEPPER1_NEGATIVELIMIT_BINDINGTYPE_STATESENSOR
#define ENTITY_STEPPER1_NEGATIVELIMIT_SENSORID 9
#define ENTITY_STEPPER1_NEGATIVELIMIT_BOUNDCHANNEL_DIGITAL_IN2
#define ENTITY_STEPPER1_NEGATIVELIMIT_STATEWHENHIGH 2
#define ENTITY_STEPPER1_NEGATIVELIMIT_STATEWHENLOW 1
#define ENTITY_STEPPER1_OUTPUTEFFECTER
#define ENTITY_STEPPER1_OUTPUTEFFECTER_BINDINGTYPE_NUMERICEFFECTER
#define ENTITY_STEPPER1_OUTPUTEFFECTER_BOUNDCHANNEL_STEP_DIR_OUT1
#define ENTITY_STEPPER1_OUTPUTENABLE
#define ENTITY_STEPPER1_OUTPUTENABLE_BINDINGTYPE_STATEEFFECTER
#define ENTITY_STEPPER1_OUTPUTENABLE_STATEWHENHIGH NULL
#define ENTITY_STEPPER1_COMMAND
#define ENTITY_STEPPER1_COMMAND_BINDINGTYPE_STATEEFFECTER
#define ENTITY_STEPPER1_COMMAND_EFFECTERID 3
#define ENTITY_STEPPER1_MOTIONSTATE
#define ENTITY_STEPPER1_MOTIONSTATE_BINDINGTYPE_STATESENSOR
#define ENTITY_STEPPER1_MOTIONSTATE_SENSORID 3
#define ENTITY_STEPPER1_PFINAL
#define ENTITY_STEPPER1_PFINAL_BINDINGTYPE_NUMERICEFFECTER
#define ENTITY_STEPPER1_PFINAL_EFFECTERID 4
#define ENTITY_STEPPER1_VPROFILE
#define ENTITY_STEPPER1_VPROFILE_BINDINGTYPE_NUMERICEFFECTER
#define ENTITY_STEPPER1_VPROFILE_EFFECTERID 5
#define ENTITY_STEPPER1_APROFILE
#define ENTITY_STEPPER1_APROFILE_BINDINGTYPE_NUMERICEFFECTER
#define ENTITY_STEPPER1_APROFILE_EFFECTERID 6
#define ENTITY_STEPPER1_PERROR
#define ENTITY_STEPPER1_PERROR_BINDINGTYPE_NUMERICSENSOR
#define ENTITY_STEPPER1_PERROR_SENSORID 5
#define ENTITY_STEPPER1_PARAM_SAMPLERATE 4000
#define ENTITY_STEPPER1_PARAM_DONETIMECONSTANT 0.01
#define ENTITY_STEPPER1_PARAM_OUTPUTINDONE_HOLD
#define ENTITY_STEPPER1_PARAM_OUTPUTINIDLE_HOLD
#define ENTITY_STEPPER1_PARAM_OUTPUTINCONDITIONSTOP_HOLD
#define ENTITY_STEPPER1_PARAM_OUTPUTINERRORSTOP_HOLD
